### PR TITLE
Update messages.po

### PR DESCRIPTION
**Pull request by astrakid**
updated german translations. will be continued...

### CODE REVIEW

**Comment by antonraharja** [comment]
please update po files inside `web/plugin` instead of `web/storage`

**Comment by astrakid** [comment]
ok, did it.
question: is the file in storage updated automatically after your commit? 
i ask because manually changing the file in /www/plugin/language/..... 
seems not to be enough (httpd restarted)...`?


regards,
anbre



Von:    Anton Raharja <notifications@github.com>
An:     antonraharja/playSMS <playSMS@noreply.github.com>
Kopie:  astrakid <andre.gronwald@gfi.ihk.de>
Datum:  04.08.2015 13:08
Betreff:        Re: [playSMS] Update messages.po (#469)



please update po files inside web/plugin instead of web/storage

**Comment by antonraharja** [comment]
Hi,

Not automatically, usually I compiled and push new files on storage. Next push you may push changes on storage but only if you have changed in plugin and compile them using contrib script.

Language files on storage folder are compiled version of po files on plugin using new contrib scripts.


anton

**Comment by astrakid** [comment]
ok,
i understood and found the relevant script to create all mo-files.
but that means that it is enough to change language files under plugin on 
github, right?

thanks a lot,
regards,
andre



Von:    Anton Raharja <notifications@github.com>
An:     antonraharja/playSMS <playSMS@noreply.github.com>
Kopie:  astrakid <andre.gronwald@gfi.ihk.de>
Datum:  04.08.2015 14:32
Betreff:        Re: [playSMS] Update messages.po (#469)



Hi,
Not automatically, usually I compiled and push new files on storage. Next 
push you may push changes on storage but only if you have changed in 
plugin and compile them using contrib script.
Language files on storage folder are compiled version of po files on 
plugin using new contrib scripts.
anton

**Comment by antonraharja** [comment]
Yes. Just change the language files under plugin and then compile them (run
the ./update-1-2-3-4.sh on contrib) to also generate the storage files.
Then you pull request (that means updates on plugin and storage).

anton

**Comment by astrakid** [comment]
ah -  i am not an expert in using github. currently i am editing 
everything via webui into the messages.po... that is not sufficient 
regarding to what you wrote, right?



Von:    Anton Raharja <notifications@github.com>
An:     antonraharja/playSMS <playSMS@noreply.github.com>
Kopie:  astrakid <andre.gronwald@gfi.ihk.de>
Datum:  04.08.2015 15:52
Betreff:        Re: [playSMS] Update messages.po (#469)



Yes. Just change the language files under plugin and then compile them 
(run
the ./update-1-2-3-4.sh on contrib) to also generate the storage files.
Then you pull request (that means updates on plugin and storage).

anton


On Tue, Aug 4, 2015 at 8:41 PM, astrakid <notifications@github.com> wrote:

> ok,
> i understood and found the relevant script to create all mo-files.
> but that means that it is enough to change language files under plugin 
on
> github, right?
>
> thanks a lot,
> regards,
> andre
>
>
>
> Von: Anton Raharja <notifications@github.com>
> An: antonraharja/playSMS <playSMS@noreply.github.com>
> Kopie: astrakid <andre.gronwald@gfi.ihk.de>
> Datum: 04.08.2015 14:32
> Betreff: Re: [playSMS] Update messages.po (#469)
>
>
>
> Hi,
> Not automatically, usually I compiled and push new files on storage. 
Next

**Pull request closed without merging**
